# Generated by Django 2.2.2 on 2019-06-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('googleId', models.CharField(max_length=30)),
                ('facebookId', models.CharField(max_length=30)),
                ('isEmailVerified', models.BooleanField(default=False)),
                ('retryCount', models.CharField(max_length=30)),
                ('emailVerificationCode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SavingDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('bankname', models.CharField(max_length=30)),
                ('account_number', models.IntegerField()),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('interest', models.IntegerField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savingdeposit.DepositUser')),
            ],
        ),
    ]
