# Generated by Django 2.2.2 on 2019-06-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingdeposit', '0002_auto_20190611_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposituser',
            name='emailVerificationCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deposituser',
            name='facebookId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deposituser',
            name='googleId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deposituser',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
