# Generated by Django 2.2.2 on 2019-06-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingdeposit', '0003_auto_20190611_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposituser',
            name='retryCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
