# Generated by Django 2.2.2 on 2019-06-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingdeposit', '0004_auto_20190611_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingdeposit',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='savingdeposit',
            name='start_date',
            field=models.DateField(),
        ),
    ]
