# Generated by Django 2.2.2 on 2019-06-25 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savingdeposit', '0006_auto_20190611_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingdeposit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DepositsUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
